lib/myapp_web/router.ex
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # plug Guardian.Plug.VerifySession
    # plug Guardian.Plug.LoadResource
    plug(MyAppWeb.Guardian.AuthBrowserPipeline)
    plug(MyAppWeb.Auth)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    # plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    # plug Guardian.Plug.LoadResource
    plug(MyAppWeb.Guardian.AuthApiPipeline)
    plug(MyAppWeb.Auth)
  end

  scope "/", MyAppWeb do
    pipe_through(:browser)
    # Index
    get("/", PageController, :index)
    # Users/ Registration
    resources("/users", UserController)
    # Accounts
    get("/accounts/:id/activation", AccountController, :show_activation_status)
    get("/accounts/:id/activation/resend", AccountController, :resend_activation)
    get("/accounts/:id/activation/:activation_token", AccountController, :activate)
    get("/accounts/password/reset", AccountController, :show_reset_password)
    post("/accounts/password/reset", AccountController, :send_password_reset_email)
    get("/accounts/password/reset/:id/:reset_token", AccountController, :show_password_change)
    post("/accounts/password/reset/:id", AccountController, :reset_password)
    # Sessions
    resources("/sessions", SessionController, only: [:new, :create, :delete])
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyAppWeb do
  #   pipe_through :api
  # end
end

lib/myapp_web/views/layout_view.ex
defmodule MyAppWeb.LayoutView do
  use MyAppWeb, :view
end

lib/myapp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= if MyAppWeb.Guardian.Plug.current_token(@conn) do %>
      <meta name='guardian_token' content="<%= MyAppWeb.Guardian.Plug.current_token(@conn) %>">
    <% end %>
    <title><%= assigns[:page_title] || "MyApp" %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/dist/app.css") %>">
    <link rel="icon" type="image/png" href="<%= static_path(@conn, "/files/favicon-32x32.png") %>" sizes="32x32" />
    <link rel="icon" type="image/png" href="<%= static_path(@conn, "/files/favicon.ico") %>" sizes="16x16" />
  </head>

  <body>
    <div class="container">
      <nav class="navbar">

        <div class="navbar-brand">
          <%= link "MyApp", to: page_path(@conn, :index), class: "navbar-item page-title is-primary" %>
          <div class="navbar-burger" data-target="nav-menu">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>

        <div class="navbar-menu" id="nav-menu">
          <!-- left side of navbar -->
          <div class="navbar-start"></div>
          <!-- right side of navbar -->
          <div class="navbar-end">
            <%= if @current_user do %>
              <%= link @current_user.username, to: user_path(@conn, :show, @current_user.id), class: "navbar-item" %>
              <%= if !@current_user.activated do %>
                <%= link "Activation Status", to: account_path(@conn, :show_activation_status, @current_user.id), class: "navbar-item" %>
              <% end %>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete", class: "navbar-item" %>
            <% else %>
              <%= link "Register", to: user_path(@conn, :new), class: "navbar-item" %>
              <%= link "Log In", to: session_path(@conn, :new), class: "navbar-item" %>
            <% end %>
          </div>
        </div>

      </nav>
    </div>

    <%= render MyAppWeb.LayoutView, "notification.html", assigns %>

    <%= render @view_module, @view_template, assigns %>
    <script src="<%= static_path(@conn, "/dist/app.js") %>"></script>
  </body>
</html>

lib/myapp_web/templates/layout/header.html.eex
<div class="title is-3"><%= @text %></div>

lib/myapp_web/templates/layout/notification.html.eex
<%= if get_flash(@conn, :info) != nil or get_flash(@conn, :error) != nil do %>
  <section class="section notification-section">
    <%= if get_flash(@conn, :info) do %>
      <div class="notification is-info">
        <button class="delete"></button>
        <%= get_flash(@conn, :info) %>
      </div>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
      <div class="notification is-warning">
        <button class="delete"></button>
        <%= get_flash(@conn, :error) %>
      </div>
    <% end %>
  </section>
<% end %>